<?php
const SUCCESS = 1;
const FAILED = 0;
const DB_CONNECTION_ERROR = "-1";

const MISSING_INFORMATION = "-101";
const USERNAME_ALREADY_EXISTS = "-102";
const EMAIL_ALREADY_EXISTS = "-103";

const INCORRECT_CREDENTIALS = "-201";

const NORMAL_USER_TYPE = 1;
const UPLOADER_TYPE = 2;
const ADMINISTRATOR_TYPE = 3;
?>