<?php
const SUCCESS = 1;
const FAILED = 0;
const DB_CONNECTION_ERROR = "-1";

const MISSING_INFORMATION = "-101";
const USERNAME_ALREADY_EXISTS = "-102";
const EMAIL_ALREADY_EXISTS = "-103";

const INCORRECT_CREDENTIALS = "-201";

const SEND_MAIL_FAILED = "-301";

const DISALLOWED_TYPE = "-401";

const NORMAL_USER_TYPE = 1;
const UPLOADER_TYPE = 2;
const ADMINISTRATOR_TYPE = 3;

const ENGINE_RPG2K = 1;
const ENGINE_RGSS = 2;
const ENGINE_RPGMV = 3;
const ENGINE_OTHER = 4;

const LANGUAGE_VIETNAMESE = 1;
const LANGUAGE_ENGLISH = 2;
const LANGUAGE_JAPANESE = 3;
const LANGUAGE_CHINESE = 4;
const LANGUAGE_OTHER = 5;
const LANGUAGE_MULTIPLE = 6;

const STATUS_DEVELOPING = 1;
const STATUS_FINISHED = 2;
const STATUS_ABANDONED = 3;
?>